# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nataly Creates
email: nataly@natalycreates.com
description: Nataly Shalem - game developer portfolio
url: "http://natalycreates.com"
twitter_username: NatalyCreates
facebook_username: natalycreates
linkedin_username: NatalyCreates
github_username:  NatalyCreates

# Build settings
markdown: kramdown

categories: [nav, games, featured, stories, photos, otherprojects]
